name: foodam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  get_it: ^8.0.3
  google_maps_flutter: ^2.12.1
  google_places_flutter: ^2.1.0
  http: ^1.3.0
  injectable: ^2.5.0
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  lottie: ^3.3.1
  path: ^1.9.1
  provider: ^6.1.4
  razorpay_flutter: ^1.4.0
  shared_preferences: ^2.5.2
  sms_autofill: ^2.4.1
  table_calendar: ^3.2.0
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/